# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subjectiveCardDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QTableWidget, QTableWidgetItem


class SubjectiveQuestions(QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("Form")
        self.resize(769, 415)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(390, 30, 91, 16))
        self.label.setObjectName("label")
        self.qid = QtWidgets.QSpinBox(self)
        self.qid.setGeometry(QtCore.QRect(60, 100, 81, 22))
        self.qid.setObjectName("qid")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(80, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(200, 70, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(61, 150, 91, 20))
        self.label_4.setObjectName("label_4")

        # 分值
        self.qvalue = QtWidgets.QSpinBox(self)
        self.qvalue.setGeometry(QtCore.QRect(180, 100, 81, 22))
        self.qvalue.setObjectName("qvalue")
        # 包含小题个数
        self.childqnumber = QtWidgets.QSpinBox(self)
        self.childqnumber.setGeometry(QtCore.QRect(60, 190, 81, 22))
        self.childqnumber.setObjectName("childqnumber")
        # 预览表格
        self.pre_form = QtWidgets.QTableWidget(self)
        self.pre_form.setGeometry(QtCore.QRect(470, 90, 237, 311))
        self.pre_form.setObjectName("pre_form_2")
        self.pre_form.setColumnCount(3)
        self.pre_form.setRowCount(1)
        # 确定键
        self.enter = QtWidgets.QPushButton(self)
        self.enter.setGeometry(QtCore.QRect(60, 260, 93, 28))
        self.enter.setObjectName("enter")

        # 删除键
        self.delquestion = QtWidgets.QPushButton(self)
        self.delquestion.setGeometry(QtCore.QRect(220, 260, 93, 28))
        self.delquestion.setObjectName("delquestion")

        self.save = QtWidgets.QPushButton(self)
        self.save.setGeometry(QtCore.QRect(60, 320, 93, 28))
        self.save.setObjectName("save")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

        self.label.setText(_translate("Form", "主观题设计"))
        self.label_2.setText(_translate("Form", "题号"))
        self.label_3.setText(_translate("Form", "分值"))
        self.label_4.setText(_translate("Form", "包含小题个数"))

        # 确定键
        self.enter.setText(_translate("Form", "确定"))
        self.enter.clicked.connect(self.insertQuestionsMessage)
        # 删除键
        self.delquestion.setText(_translate("Form", "删除"))
        self.delquestion.clicked.connect(self.delOneHeader)
        # 保存键
        self.save.setText(_translate("Form", "保存"))


        # 设置预览表格
        self.pre_form.setColumnCount(4)
        self.pre_form.setRowCount(1)
        self.pre_form.resizeRowsToContents()
        self.pre_form.resizeColumnsToContents()
        # 设置表头
        horizontalHeader = ["题号", "小题个数", "分值"]
        self.pre_form.setHorizontalHeaderLabels(horizontalHeader)
        # 设置列宽
        for index in range(self.pre_form.colorCount()):
            self.pre_form.setColumnWidth(index, 80)
        # 设置不可编辑
        self.pre_form.setEditTriggers(QTableWidget.NoEditTriggers)
        self.pre_form.verticalHeader().hide()

    def insertQuestionsMessage(self):
        qid = self.qid.value()
        childqnumber = self.childqnumber.value()
        qvalue = self.qvalue.value()
        # 插入行
        row_count = self.pre_form.rowCount()
        self.pre_form.insertRow(row_count)

        self.pre_form.setItem(row_count, 0, QTableWidgetItem(str(qid)))
        self.pre_form.setItem(row_count, 1, QTableWidgetItem(str(childqnumber)))
        self.pre_form.setItem(row_count, 2, QTableWidgetItem(str(qvalue)))


    def delOneHeader(self):
        row_count = self.pre_form.rowCount()
        self.pre_form.removeRow(row_count - 1)
# import sys
# app = QtWidgets.QApplication(sys.argv)
# ui = Ui_Form()
# ui.show()
# sys.exit(app.exec_())
